### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by cfunseth** [Jacen-crudo/Bluebeam-Stamp-DiagBox#1]
I don't have any issues with your code, but instead wanted to thank you for posting this! I just dove into interactive stamps with Bluebeam and was very perplexed at the lack of documentation. I just used your code and had a working stamp in less than 30 minutes. I didn't notice any immediate issues (aside from tab not working in the Bluebeam editor window), so you did a fantastic job in pulling this together.

Thanks!

**Comment by Jacen-crudo** [comment]
Thank you for the response! This was a project that really helped me re-develop a passion for coding and development. This was work I did at my old job and it was something I just wanted to tackle. Thank you for the like!
