### ISSUE TITLE
Step 12 of the PDF references the wrong javascript file

### ISSUE THREAD

**Issue by garylzimmer** [Jacen-crudo/Bluebeam-Stamp-DiagBox#2]
Step 12 references the diagBuilderCode.js file which is incorrect, it should be referencing the diagBuilderData.js file that was edited the steps leading up to it.

I figured it out and got it all working and very happy with all the doors this opens up for me!
Thanks so much!!

**Comment by Jacen-crudo** [comment]
I've updated the reference guide and changed the naming scheme to accomodate. Thank you for the report :)
